version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ml_postgres

    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana123
      POSTGRES_DB: mlproject

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    container_name: ml_grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123

    depends_on:
      - postgres

volumes:
  postgres_data: